### ISSUE TITLE
submodule usage

### ISSUE THREAD

**Issue by berkkarahan** [HOWZ1T/py_proxy#4]
hey again,
you should add a ___init___.py file in order to use this as a submodule in other project.s

**Comment by HOWZ1T** [comment]
Hey Berkkarahan,

This project is a single file module, due to it having only 1 class and being relatively small.
It is intended to be a library thus it is available as a pypi package from https://pypi.org/project/py-proxy/

This python module can be used in any other python code by just importing it.
For more on python modules feel free to read: https://docs.python.org/3/tutorial/modules.html

What you are referring to are packages, they generally have __init__.py modules to help organize the code contained within the package and specify how it can be imported by other users of the package.

Since this project is small, it is currently not necessary to convert its' structure to that of a package.

If you have anymore questions feel free to contact me.

All the best,
Dylan
