### ISSUE TITLE
continues to fail, gets no working proxy

### ISSUE THREAD

**Issue by mujeebishaque** [HOWZ1T/py_proxy#9]
I have been trying to run the module but to vain. All the proxies that the module fetches are failing and none of them work. Can you please look into it and check why do all proxies are failing? Thanks.

**Comment by HOWZ1T** [comment]
Sure, I'll check it out tomorrow and get back to you within a day or so.

**Comment by mujeebishaque** [comment]
Thank you so much! Respects.

**Comment by HOWZ1T** [comment]
I've had a look into it and it is still able to correctly fetch the proxies. Some of the proxies it fetches are dead, however that is normal and means that it will fail when tested. 

As for all proxies failing it might be due to bad SSL certificates on the website used to test the proxy or a bad SSL connection formed from the device running the test to the website.

At this time I'm unable to 'fix' the SSL issue as it is an issue on the machine running the package and/or the server used to test the proxy.
